Repository QubesOS/qubes-doc, pull requests merged in 2022-02, with the labels that each got.

#1166 GuiVM documentation
  user/advanced-topics/guivm.md
Labels: R4.1

#1193 Update how-to-update.md
  user/how-to-guides/how-to-update.md
Labels: R4.1

#1189 Add GRUB installation steps to managing-vm-kernels.md
  user/advanced-topics/managing-vm-kernels.md
Labels: waiting for review

#1220 Updated instructions with new gpg version and removed depreciated keyserver
  developer/code/code-signing.md
Labels: waiting for review

#1225 Document improved USB HID handling on Qubes 4.1
  user/advanced-topics/disposable-customization.md
  user/advanced-topics/usb-qubes.md
  user/downloading-installing-upgrading/install-security.md
  user/how-to-guides/how-to-use-usb-devices.md
  user/troubleshooting/usb-troubleshooting.md
Labels: R4.1, waiting for author
